<?php

namespace frontend\models\rest;

use frontend\models\PlayerResources;
use Yii;

/**
 * This is the model class for table "player_resources".
 *
 * @property int $id_player
 * @property int $points
 * @property int $level
 * @property int $clan_id
 * @property int $safe_skull
 * @property int $safe_vodka
 * @property string $friends
 * @property int $location
 * @property int $place
 */
class OpenResources extends PlayerResources
{
    public function fields()
    {
//        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return [
            'points',
            'level',
            'clan_id',
            'location',
            'place',
        ];
    }
}
